# Hide default refind text, ui elements
hideui arrows,hints,label,badges

# Set icon directory
# For 2/3 scale icon set change to 'themes/refindTTT/icons176' & change icon sizes, selection backgrounds
icons_dir themes/refindTTT/icons

# Set background
# Custom backgrounds won't work well unless they are almost entirely black
banner themes/refindTTT/backgrounds/background.png
banner_scale fillscreen

# Set icon sizes
# For 2/3 scale icon set change to small: 90, big: 176. Also change icons_dir, selection backgrounds to 176
small_icon_size 120
big_icon_size 256

# Make boot a little cleaner
use_graphics_for osx,linux,elilo,grub,windows

# Set background for selected option
# To hide text label change to 'selection_big_nolabels.png', 'selection_small_nolabels.png'
# For 2/3 scale icon set change to 'selection_big176.png', 'selection_small176.png'
selection_big   themes/refindTTT/backgrounds/selection_big.png
selection_small themes/refindTTT/backgrounds/selection_small.png

# Set maximum icons to display at a time
max_tags 7

# Set delay before automatic boot
timeout 10
